Pullup ticket #4889 - requested by leot print/gv: bugfix
Revisions pulled up:
- print/gv/Makefile                                             1.84

---
   Module Name:	pkgsrc
   Committed By:	markd
   Date:		Wed Jan  6 10:14:10 UTC 2016

   Modified Files:
   	pkgsrc/print/gv: Makefile

   Log Message:
   Use pkg-config when building so that correct defines are used when
   building against libXaw3d.  Fixes problem that gv would fail with the
   error:
   Warning: Representation size 4 must match superclass's to override highlightedFrameStyle
   Error: Object "toggleEven" does not have windowed ancestor