Update to Tomcat 6.0.44
Upstream changelog:

Catalina
++++++++
fix	Correct typo in the message shown by HttpServlet for unexpected
	HTTP method. (kkolinko)
add	Allow to configure RemoteAddrValve and RemoteHostValve to adopt
	behavior depending on the connector port. Implemented by
	optionally adding the connector port to the string compared with
	the patterns allow and deny. Configured using addConnectorPort
	attribute on valve. (rjung)
fix	56608: Fix IllegalStateException for JavaScript files when
	switching from Writer to OutputStream. The special handling of
	this case in the DefaultServlet was broken due to a MIME type
	change for JavaScript. (markt)
fix	57675: Correctly quote strings when using the extended access
	log. (markt)

Coyote
++++++
fix	57234: Make SSL protocol filtering to remove insecure protocols
	case insensitive. Correct spelling of filterInsecureProtocols
	method. (kkolinko/schultz)
fix	When applying the maxSwallowSize limit to a connection read
	that many bytes first before closing the connection to give
	the client a chance to read the response. (markt)
fix	57544: Fix a potential infinite loop when preparing a kept
	alive HTTP connection for the next request. (markt)
add	57570: Make the processing of chunked encoding trailing headers
	optional and disabled by default. (markt)
fix	57581: Change statistics byte counter in coyote Request object
	to be long to allow values above 2Gb. (kkolinko)
update	Update the minimum recommended version of the Tomcat Native
	library (if used) to 1.1.33. (markt)

Jasper
++++++
fix	Fix potential issue with BeanELResolver when running under a
	security manager. Some classes may not be accessible but may
	have accessible interfaces. (markt)
fix	Simplify code in ProtectedFunctionMapper class of Jasper
	runtime. (kkolinko)
fix	57801: Improve the error message in the start script in case
	the PID read from the PID file is already owned by a process.
	(rjung)

Web applications
++++++++++++++++
fix	Update documentation for CGI servlet. Recommend to copy the
	servlet declaration into web application instead of enabling
	it globally. Correct documentation for cgiPathPrefix. (kkolinko)
update	Improve Tomcat Manager documentation. Rearrange, add section
	on HTML GUI, document /expire command and Server Status page.
	(kkolinko)
add	54143: Add display of the memory pools usage (including PermGen)
	to the Status page of the Manager web application. (kkolinko)
fix	Fix several issues with status.xsd schema in Manager web
	application, testing it against actual output of
	StatusTransformer class. (kkolinko)
update	Align algorithm that generates anchor names in Tomcat
	documentation with Tomcat 7/8/9. No visible changes, but may
	help with future updates to the documentation. (kkolinko)
fix	56058: Add links to the AccessLogValve documentation for
	configuring reverse proxies and/or Tomcat to ensure that the
	desired information is used entered in the access log when
	Tomcat is running behind a reverse proxy. (markt)
fix	57503: Make clear that the JULI integration for log4j only
	works with log4j 1.2.x. (markt)
update	57644: Update examples to use Apache Standard Taglib 1.2.5.
	(jboynes/kkolinko)
fix	57706: Clarify the documentation for the AJP connector to make
	clearer that when using tomcatAuthentication="false" the user
	provided by the reverse proxy will not be associated with any
	roles. (markt)
fix	Correct the documentation for deployOnStartup to make clear
	that if a WAR file is updated while Tomcat is stopped and
	unpackWARs is true, Tomcat will not detect the changed WAR
	file when it starts and will not replace the unpacked WAR file
	with the contents of the updated WAR. (markt)
add	57759: Add information to the keyAlias documentation to make
	it clear that the order keys are read from the keystore is
	implementation dependent. (markt)
fix	57864: Update the documentation web application to make it
	clearer that hex values are not valid for cluster send options.
	Based on a patch by Kyohei Nakamura. (markt)

Other
+++++
add	57344: Provide sha1 checksum files for Tomcat downloads.
	(kkolinko)
fix	57558: Change catalina-tasks.xml to use all jars in
	${catalina.home}/lib to define Tomcat Ant tasks. This fixes
	a NoClassDefFoundError with validate task. (kkolinko)
update	Update to Tomcat Native Library version 1.1.33 to pick up the
	Windows binaries that are based on OpenSSL 1.0.1m and APR 1.5.1.
	(markt)